#!/bin/bash
method='dd'

usage() {
	cat <<EOF
$0 [-hmv] 
-h Print a usage statement and exit.
-m method Use the given method to perform the backup. Valid method are 'dd' and 'rsync'; default is 'dd'.
-v volume-id  Use the given volume instead of creating a new one.
EOF
}

while getopts h:m:v flag; do
  case "${flag}" in
    h) usage ;; 
    m) method=$OPTARG ;;
    v) volumeid=$OPTARG;;
    *) usage
	   exit 1
	   ;;
  esac
done

echo $method
